//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SPMOResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPMOResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SPMOResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will be activate after 48 hours..
        /// </summary>
        internal static string AccountActivate {
            get {
                return ResourceManager.GetString("AccountActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panchayat login service not available now..
        /// </summary>
        internal static string AgentLogin {
            get {
                return ResourceManager.GetString("AgentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such information already exist..
        /// </summary>
        internal static string AlreadyExist {
            get {
                return ResourceManager.GetString("AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact administrator..
        /// </summary>
        internal static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to save information..
        /// </summary>
        internal static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently you are on first page..
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been sent on registered mobile number, Please do login with same..
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information saved successfully..
        /// </summary>
        internal static string InformationSave {
            get {
                return ResourceManager.GetString("InformationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP, Please feel valid OTP..
        /// </summary>
        internal static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not belongs to system..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Name or Password..
        /// </summary>
        internal static string InvalidUserNamePassword {
            get {
                return ResourceManager.GetString("InvalidUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your mail id was confirmed. Please complete your profile..
        /// </summary>
        internal static string MailConfirmation {
            get {
                return ResourceManager.GetString("MailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more information availble..
        /// </summary>
        internal static string NoMoreInformationAvail {
            get {
                return ResourceManager.GetString("NoMoreInformationAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records to display..
        /// </summary>
        internal static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP has been expired Please Generate OTP again..
        /// </summary>
        internal static string OTPExpired {
            get {
                return ResourceManager.GetString("OTPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to register user..
        /// </summary>
        internal static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered successfully..
        /// </summary>
        internal static string RegistrationPage {
            get {
                return ResourceManager.GetString("RegistrationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request already sent for approval..
        /// </summary>
        internal static string RequestAlreadySent {
            get {
                return ResourceManager.GetString("RequestAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do login before send request..
        /// </summary>
        internal static string RequestLogin {
            get {
                return ResourceManager.GetString("RequestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been sent for approval..
        /// </summary>
        internal static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to send request..
        /// </summary>
        internal static string RequestSentFailed {
            get {
                return ResourceManager.GetString("RequestSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already another user registered with same mobile number..
        /// </summary>
        internal static string SameUserExist {
            get {
                return ResourceManager.GetString("SameUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information updated successfully..
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information saved successfully..
        /// </summary>
        internal static string UserInformationSave {
            get {
                return ResourceManager.GetString("UserInformationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to save user information..
        /// </summary>
        internal static string UserinformationSaveFailed {
            get {
                return ResourceManager.GetString("UserinformationSaveFailed", resourceCulture);
            }
        }
    }
}
